name: GitHub Actions Demo

on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '50 * * * *'
  ## also run on push events
  push:
    branches:
      - master

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v0.0.0
      - name: install dependencies
        run: sudo apt-get install -y pngcrush jo jq
      - name: run the cron.sh script to generate new display.png
        run: ./cron.sh
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
      - run: echo "🍏 This job's status is ${{ job.status }}."
